package ECOMML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ShipmentStatus extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ShipmentStatus() {
    super(0xec1bc844bf74e86L, 0x9b15a8f6767d0e4eL, 0x4c007588fdc61ca7L, "ShipmentStatus", "r:574a9064-41ef-49c4-a078-66bb8bceb412(ECOMML.structure)/5476506378116144295");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_pending_0 = new EnumerationDescriptor.MemberDescriptor("pending", "pending", 0x4c007588fdc61ca8L, "r:574a9064-41ef-49c4-a078-66bb8bceb412(ECOMML.structure)/5476506378116144296");
  private final EnumerationDescriptor.MemberDescriptor myMember_traveling_0 = new EnumerationDescriptor.MemberDescriptor("traveling", "traveling", 0x4c007588fdc61ca9L, "r:574a9064-41ef-49c4-a078-66bb8bceb412(ECOMML.structure)/5476506378116144297");
  private final EnumerationDescriptor.MemberDescriptor myMember_delivered_0 = new EnumerationDescriptor.MemberDescriptor("delivered", "delivered", 0x4c007588fdc61cacL, "r:574a9064-41ef-49c4-a078-66bb8bceb412(ECOMML.structure)/5476506378116144300");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0xec1bc844bf74e86L, 0x9b15a8f6767d0e4eL, 0x4c007588fdc61ca7L, 0x4c007588fdc61ca8L, 0x4c007588fdc61ca9L, 0x4c007588fdc61cacL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_pending_0, myMember_traveling_0, myMember_delivered_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "pending":
        return myMember_pending_0;
      case "traveling":
        return myMember_traveling_0;
      case "delivered":
        return myMember_delivered_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
