package ECOMML.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Address = 0;
  public static final int Administrator = 1;
  public static final int Cart = 2;
  public static final int Category = 3;
  public static final int Customer = 4;
  public static final int EcommerceSystem = 5;
  public static final int Invoice = 6;
  public static final int ItemCart = 7;
  public static final int Order = 8;
  public static final int Product = 9;
  public static final int ProductImage = 10;
  public static final int Shipment = 11;
  public static final int User = 12;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0xec1bc844bf74e86L, 0x9b15a8f6767d0e4eL);
    builder.put(0x15d9852c2ef09ff4L, Address);
    builder.put(0x15d9852c2ef0a049L, Administrator);
    builder.put(0x15d9852c2ef09f4bL, Cart);
    builder.put(0x15d9852c2ef09f45L, Category);
    builder.put(0x15d9852c2ef0a04cL, Customer);
    builder.put(0x15d9852c2ef09f15L, EcommerceSystem);
    builder.put(0x15d9852c2ef0a038L, Invoice);
    builder.put(0x15d9852c2ef09fe8L, ItemCart);
    builder.put(0x15d9852c2ef0a01aL, Order);
    builder.put(0x15d9852c2ef09f48L, Product);
    builder.put(0x4c007588fdc61c56L, ProductImage);
    builder.put(0x4c007588fdc61c7fL, Shipment);
    builder.put(0x15d9852c2ef09f42L, User);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
