/**
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.ecommerce.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.disim.univaq.ecommerce.xtext.EcommerceRuntimeModule;
import it.disim.univaq.ecommerce.xtext.EcommerceStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class EcommerceIdeSetup extends EcommerceStandaloneSetup {
  @Override
  public Injector createInjector() {
    EcommerceRuntimeModule _ecommerceRuntimeModule = new EcommerceRuntimeModule();
    EcommerceIdeModule _ecommerceIdeModule = new EcommerceIdeModule();
    return Guice.createInjector(Modules2.mixin(_ecommerceRuntimeModule, _ecommerceIdeModule));
  }
}
