/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.ecommerce.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class EcommerceGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class EcommerceSystemElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.EcommerceSystem");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cEcommerceSystemKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCategoriesKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cShop_have_categoriesAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cShop_have_categoriesCategoryParserRuleCall_3_2_0 = (RuleCall)cShop_have_categoriesAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cShop_have_categoriesAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cShop_have_categoriesCategoryParserRuleCall_3_3_1_0 = (RuleCall)cShop_have_categoriesAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCustomersKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cHave_clientsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cHave_clientsCustomerParserRuleCall_4_2_0 = (RuleCall)cHave_clientsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cHave_clientsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cHave_clientsCustomerParserRuleCall_4_3_1_0 = (RuleCall)cHave_clientsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cAdministratorsKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cShop_have_administratorsAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cShop_have_administratorsAdministratorParserRuleCall_5_2_0 = (RuleCall)cShop_have_administratorsAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cShop_have_administratorsAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cShop_have_administratorsAdministratorParserRuleCall_5_3_1_0 = (RuleCall)cShop_have_administratorsAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//EcommerceSystem returns EcommerceSystem:
		//    'EcommerceSystem'
		//    name=EString
		//    '{'
		//        ('categories' '[' shop_have_categories+=Category ( "," shop_have_categories+=Category)* ']' )?
		//        ('customers' '[' have_clients+=Customer ( "," have_clients+=Customer)* ']' )?
		//        ('administrators' '[' shop_have_administrators+=Administrator ( "," shop_have_administrators+=Administrator)* ']' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'EcommerceSystem'
		//name=EString
		//'{'
		//    ('categories' '[' shop_have_categories+=Category ( "," shop_have_categories+=Category)* ']' )?
		//    ('customers' '[' have_clients+=Customer ( "," have_clients+=Customer)* ']' )?
		//    ('administrators' '[' shop_have_administrators+=Administrator ( "," shop_have_administrators+=Administrator)* ']' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'EcommerceSystem'
		public Keyword getEcommerceSystemKeyword_0() { return cEcommerceSystemKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('categories' '[' shop_have_categories+=Category ( "," shop_have_categories+=Category)* ']' )?
		public Group getGroup_3() { return cGroup_3; }
		
		//'categories'
		public Keyword getCategoriesKeyword_3_0() { return cCategoriesKeyword_3_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_3_1() { return cLeftSquareBracketKeyword_3_1; }
		
		//shop_have_categories+=Category
		public Assignment getShop_have_categoriesAssignment_3_2() { return cShop_have_categoriesAssignment_3_2; }
		
		//Category
		public RuleCall getShop_have_categoriesCategoryParserRuleCall_3_2_0() { return cShop_have_categoriesCategoryParserRuleCall_3_2_0; }
		
		//( "," shop_have_categories+=Category)*
		public Group getGroup_3_3() { return cGroup_3_3; }
		
		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }
		
		//shop_have_categories+=Category
		public Assignment getShop_have_categoriesAssignment_3_3_1() { return cShop_have_categoriesAssignment_3_3_1; }
		
		//Category
		public RuleCall getShop_have_categoriesCategoryParserRuleCall_3_3_1_0() { return cShop_have_categoriesCategoryParserRuleCall_3_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_3_4() { return cRightSquareBracketKeyword_3_4; }
		
		//('customers' '[' have_clients+=Customer ( "," have_clients+=Customer)* ']' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'customers'
		public Keyword getCustomersKeyword_4_0() { return cCustomersKeyword_4_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_4_1() { return cLeftSquareBracketKeyword_4_1; }
		
		//have_clients+=Customer
		public Assignment getHave_clientsAssignment_4_2() { return cHave_clientsAssignment_4_2; }
		
		//Customer
		public RuleCall getHave_clientsCustomerParserRuleCall_4_2_0() { return cHave_clientsCustomerParserRuleCall_4_2_0; }
		
		//( "," have_clients+=Customer)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//have_clients+=Customer
		public Assignment getHave_clientsAssignment_4_3_1() { return cHave_clientsAssignment_4_3_1; }
		
		//Customer
		public RuleCall getHave_clientsCustomerParserRuleCall_4_3_1_0() { return cHave_clientsCustomerParserRuleCall_4_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_4_4() { return cRightSquareBracketKeyword_4_4; }
		
		//('administrators' '[' shop_have_administrators+=Administrator ( "," shop_have_administrators+=Administrator)* ']' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'administrators'
		public Keyword getAdministratorsKeyword_5_0() { return cAdministratorsKeyword_5_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5_1() { return cLeftSquareBracketKeyword_5_1; }
		
		//shop_have_administrators+=Administrator
		public Assignment getShop_have_administratorsAssignment_5_2() { return cShop_have_administratorsAssignment_5_2; }
		
		//Administrator
		public RuleCall getShop_have_administratorsAdministratorParserRuleCall_5_2_0() { return cShop_have_administratorsAdministratorParserRuleCall_5_2_0; }
		
		//( "," shop_have_administrators+=Administrator)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//shop_have_administrators+=Administrator
		public Assignment getShop_have_administratorsAssignment_5_3_1() { return cShop_have_administratorsAssignment_5_3_1; }
		
		//Administrator
		public RuleCall getShop_have_administratorsAdministratorParserRuleCall_5_3_1_0() { return cShop_have_administratorsAdministratorParserRuleCall_5_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5_4() { return cRightSquareBracketKeyword_5_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}
	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//    STRING | ID;
		@Override public ParserRule getRule() { return rule; }
		
		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}
	public class CategoryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.Category");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCategoryKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActiveKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActiveAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cActiveEBooleanParserRuleCall_3_1_0 = (RuleCall)cActiveAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cRoot_catKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cRoot_catAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cRoot_catEBooleanParserRuleCall_4_1_0 = (RuleCall)cRoot_catAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cSub_categoriesKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cHave_sub_categoriesAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cHave_sub_categoriesCategoryParserRuleCall_5_2_0 = (RuleCall)cHave_sub_categoriesAssignment_5_2.eContents().get(0);
		private final Group cGroup_5_3 = (Group)cGroup_5.eContents().get(3);
		private final Keyword cCommaKeyword_5_3_0 = (Keyword)cGroup_5_3.eContents().get(0);
		private final Assignment cHave_sub_categoriesAssignment_5_3_1 = (Assignment)cGroup_5_3.eContents().get(1);
		private final RuleCall cHave_sub_categoriesCategoryParserRuleCall_5_3_1_0 = (RuleCall)cHave_sub_categoriesAssignment_5_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cProductsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cHave_productsAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cHave_productsProductParserRuleCall_6_2_0 = (RuleCall)cHave_productsAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cHave_productsAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cHave_productsProductParserRuleCall_6_3_1_0 = (RuleCall)cHave_productsAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Category returns Category:
		//    'Category'
		//    name=EString
		//    '{'
		//        ('active:' active=EBoolean)
		//        ('root_cat:' root_cat=EBoolean)
		//        ('sub_categories' '[' have_sub_categories+=Category ( "," have_sub_categories+=Category)* ']' )?
		//        ('products' '[' have_products+=Product ( "," have_products+=Product)* ']' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Category'
		//name=EString
		//'{'
		//    ('active:' active=EBoolean)
		//    ('root_cat:' root_cat=EBoolean)
		//    ('sub_categories' '[' have_sub_categories+=Category ( "," have_sub_categories+=Category)* ']' )?
		//    ('products' '[' have_products+=Product ( "," have_products+=Product)* ']' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Category'
		public Keyword getCategoryKeyword_0() { return cCategoryKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('active:' active=EBoolean)
		public Group getGroup_3() { return cGroup_3; }
		
		//'active:'
		public Keyword getActiveKeyword_3_0() { return cActiveKeyword_3_0; }
		
		//active=EBoolean
		public Assignment getActiveAssignment_3_1() { return cActiveAssignment_3_1; }
		
		//EBoolean
		public RuleCall getActiveEBooleanParserRuleCall_3_1_0() { return cActiveEBooleanParserRuleCall_3_1_0; }
		
		//('root_cat:' root_cat=EBoolean)
		public Group getGroup_4() { return cGroup_4; }
		
		//'root_cat:'
		public Keyword getRoot_catKeyword_4_0() { return cRoot_catKeyword_4_0; }
		
		//root_cat=EBoolean
		public Assignment getRoot_catAssignment_4_1() { return cRoot_catAssignment_4_1; }
		
		//EBoolean
		public RuleCall getRoot_catEBooleanParserRuleCall_4_1_0() { return cRoot_catEBooleanParserRuleCall_4_1_0; }
		
		//('sub_categories' '[' have_sub_categories+=Category ( "," have_sub_categories+=Category)* ']' )?
		public Group getGroup_5() { return cGroup_5; }
		
		//'sub_categories'
		public Keyword getSub_categoriesKeyword_5_0() { return cSub_categoriesKeyword_5_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_5_1() { return cLeftSquareBracketKeyword_5_1; }
		
		//have_sub_categories+=Category
		public Assignment getHave_sub_categoriesAssignment_5_2() { return cHave_sub_categoriesAssignment_5_2; }
		
		//Category
		public RuleCall getHave_sub_categoriesCategoryParserRuleCall_5_2_0() { return cHave_sub_categoriesCategoryParserRuleCall_5_2_0; }
		
		//( "," have_sub_categories+=Category)*
		public Group getGroup_5_3() { return cGroup_5_3; }
		
		//","
		public Keyword getCommaKeyword_5_3_0() { return cCommaKeyword_5_3_0; }
		
		//have_sub_categories+=Category
		public Assignment getHave_sub_categoriesAssignment_5_3_1() { return cHave_sub_categoriesAssignment_5_3_1; }
		
		//Category
		public RuleCall getHave_sub_categoriesCategoryParserRuleCall_5_3_1_0() { return cHave_sub_categoriesCategoryParserRuleCall_5_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_5_4() { return cRightSquareBracketKeyword_5_4; }
		
		//('products' '[' have_products+=Product ( "," have_products+=Product)* ']' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'products'
		public Keyword getProductsKeyword_6_0() { return cProductsKeyword_6_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_6_1() { return cLeftSquareBracketKeyword_6_1; }
		
		//have_products+=Product
		public Assignment getHave_productsAssignment_6_2() { return cHave_productsAssignment_6_2; }
		
		//Product
		public RuleCall getHave_productsProductParserRuleCall_6_2_0() { return cHave_productsProductParserRuleCall_6_2_0; }
		
		//( "," have_products+=Product)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//have_products+=Product
		public Assignment getHave_productsAssignment_6_3_1() { return cHave_productsAssignment_6_3_1; }
		
		//Product
		public RuleCall getHave_productsProductParserRuleCall_6_3_1_0() { return cHave_productsProductParserRuleCall_6_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_6_4() { return cRightSquareBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class CustomerElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.Customer");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCustomerKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActiveKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActiveAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cActiveEBooleanParserRuleCall_3_1_0 = (RuleCall)cActiveAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSurnameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSurnameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cSurnameEStringParserRuleCall_4_1_0 = (RuleCall)cSurnameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cUsernameKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cUsernameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cUsernameEStringParserRuleCall_5_1_0 = (RuleCall)cUsernameAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPasswordKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPasswordAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPasswordEStringParserRuleCall_6_1_0 = (RuleCall)cPasswordAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cEmailKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cEmailAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cEmailEStringParserRuleCall_7_1_0 = (RuleCall)cEmailAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cAddressKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_8_1 = (Keyword)cGroup_8.eContents().get(1);
		private final Assignment cCustomer_have_addressAssignment_8_2 = (Assignment)cGroup_8.eContents().get(2);
		private final RuleCall cCustomer_have_addressAddressParserRuleCall_8_2_0 = (RuleCall)cCustomer_have_addressAssignment_8_2.eContents().get(0);
		private final Group cGroup_8_3 = (Group)cGroup_8.eContents().get(3);
		private final Keyword cCommaKeyword_8_3_0 = (Keyword)cGroup_8_3.eContents().get(0);
		private final Assignment cCustomer_have_addressAssignment_8_3_1 = (Assignment)cGroup_8_3.eContents().get(1);
		private final RuleCall cCustomer_have_addressAddressParserRuleCall_8_3_1_0 = (RuleCall)cCustomer_have_addressAssignment_8_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8_4 = (Keyword)cGroup_8.eContents().get(4);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cCartKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cCustomer_have_cartAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cCustomer_have_cartCartParserRuleCall_9_2_0 = (RuleCall)cCustomer_have_cartAssignment_9_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9_3 = (Keyword)cGroup_9.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Customer returns Customer:
		//    'Customer'
		//    name=EString
		//    '{'
		//        ('active:' active=EBoolean)
		//        ('surname:' surname=EString)?
		//        ('username:' username=EString)?
		//        ('password:' password=EString)?
		//        ('email:' email=EString)?
		//        ('address' '{' customer_have_address+=Address ( "," customer_have_address+=Address)* '}' )
		//        ('cart' '{' customer_have_cart=Cart '}')?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Customer'
		//name=EString
		//'{'
		//    ('active:' active=EBoolean)
		//    ('surname:' surname=EString)?
		//    ('username:' username=EString)?
		//    ('password:' password=EString)?
		//    ('email:' email=EString)?
		//    ('address' '{' customer_have_address+=Address ( "," customer_have_address+=Address)* '}' )
		//    ('cart' '{' customer_have_cart=Cart '}')?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Customer'
		public Keyword getCustomerKeyword_0() { return cCustomerKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('active:' active=EBoolean)
		public Group getGroup_3() { return cGroup_3; }
		
		//'active:'
		public Keyword getActiveKeyword_3_0() { return cActiveKeyword_3_0; }
		
		//active=EBoolean
		public Assignment getActiveAssignment_3_1() { return cActiveAssignment_3_1; }
		
		//EBoolean
		public RuleCall getActiveEBooleanParserRuleCall_3_1_0() { return cActiveEBooleanParserRuleCall_3_1_0; }
		
		//('surname:' surname=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'surname:'
		public Keyword getSurnameKeyword_4_0() { return cSurnameKeyword_4_0; }
		
		//surname=EString
		public Assignment getSurnameAssignment_4_1() { return cSurnameAssignment_4_1; }
		
		//EString
		public RuleCall getSurnameEStringParserRuleCall_4_1_0() { return cSurnameEStringParserRuleCall_4_1_0; }
		
		//('username:' username=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'username:'
		public Keyword getUsernameKeyword_5_0() { return cUsernameKeyword_5_0; }
		
		//username=EString
		public Assignment getUsernameAssignment_5_1() { return cUsernameAssignment_5_1; }
		
		//EString
		public RuleCall getUsernameEStringParserRuleCall_5_1_0() { return cUsernameEStringParserRuleCall_5_1_0; }
		
		//('password:' password=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'password:'
		public Keyword getPasswordKeyword_6_0() { return cPasswordKeyword_6_0; }
		
		//password=EString
		public Assignment getPasswordAssignment_6_1() { return cPasswordAssignment_6_1; }
		
		//EString
		public RuleCall getPasswordEStringParserRuleCall_6_1_0() { return cPasswordEStringParserRuleCall_6_1_0; }
		
		//('email:' email=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'email:'
		public Keyword getEmailKeyword_7_0() { return cEmailKeyword_7_0; }
		
		//email=EString
		public Assignment getEmailAssignment_7_1() { return cEmailAssignment_7_1; }
		
		//EString
		public RuleCall getEmailEStringParserRuleCall_7_1_0() { return cEmailEStringParserRuleCall_7_1_0; }
		
		//('address' '{' customer_have_address+=Address ( "," customer_have_address+=Address)* '}' )
		public Group getGroup_8() { return cGroup_8; }
		
		//'address'
		public Keyword getAddressKeyword_8_0() { return cAddressKeyword_8_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_8_1() { return cLeftCurlyBracketKeyword_8_1; }
		
		//customer_have_address+=Address
		public Assignment getCustomer_have_addressAssignment_8_2() { return cCustomer_have_addressAssignment_8_2; }
		
		//Address
		public RuleCall getCustomer_have_addressAddressParserRuleCall_8_2_0() { return cCustomer_have_addressAddressParserRuleCall_8_2_0; }
		
		//( "," customer_have_address+=Address)*
		public Group getGroup_8_3() { return cGroup_8_3; }
		
		//","
		public Keyword getCommaKeyword_8_3_0() { return cCommaKeyword_8_3_0; }
		
		//customer_have_address+=Address
		public Assignment getCustomer_have_addressAssignment_8_3_1() { return cCustomer_have_addressAssignment_8_3_1; }
		
		//Address
		public RuleCall getCustomer_have_addressAddressParserRuleCall_8_3_1_0() { return cCustomer_have_addressAddressParserRuleCall_8_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8_4() { return cRightCurlyBracketKeyword_8_4; }
		
		//('cart' '{' customer_have_cart=Cart '}')?
		public Group getGroup_9() { return cGroup_9; }
		
		//'cart'
		public Keyword getCartKeyword_9_0() { return cCartKeyword_9_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_9_1() { return cLeftCurlyBracketKeyword_9_1; }
		
		//customer_have_cart=Cart
		public Assignment getCustomer_have_cartAssignment_9_2() { return cCustomer_have_cartAssignment_9_2; }
		
		//Cart
		public RuleCall getCustomer_have_cartCartParserRuleCall_9_2_0() { return cCustomer_have_cartCartParserRuleCall_9_2_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_9_3() { return cRightCurlyBracketKeyword_9_3; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class AdministratorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.Administrator");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAdministratorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActiveKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActiveAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cActiveEBooleanParserRuleCall_3_1_0 = (RuleCall)cActiveAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cSurnameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cSurnameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cSurnameEStringParserRuleCall_4_1_0 = (RuleCall)cSurnameAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cUsernameKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cUsernameAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cUsernameEStringParserRuleCall_5_1_0 = (RuleCall)cUsernameAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cPasswordKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cPasswordAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cPasswordEStringParserRuleCall_6_1_0 = (RuleCall)cPasswordAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cEmailKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cEmailAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cEmailEStringParserRuleCall_7_1_0 = (RuleCall)cEmailAssignment_7_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_8 = (Keyword)cGroup.eContents().get(8);
		
		//Administrator returns Administrator:
		//    'Administrator'
		//    name=EString
		//    '{'
		//        ('active:' active=EBoolean)
		//        ('surname:' surname=EString)?
		//        ('username:' username=EString)?
		//        ('password:' password=EString)?
		//        ('email:' email=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Administrator'
		//name=EString
		//'{'
		//    ('active:' active=EBoolean)
		//    ('surname:' surname=EString)?
		//    ('username:' username=EString)?
		//    ('password:' password=EString)?
		//    ('email:' email=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Administrator'
		public Keyword getAdministratorKeyword_0() { return cAdministratorKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('active:' active=EBoolean)
		public Group getGroup_3() { return cGroup_3; }
		
		//'active:'
		public Keyword getActiveKeyword_3_0() { return cActiveKeyword_3_0; }
		
		//active=EBoolean
		public Assignment getActiveAssignment_3_1() { return cActiveAssignment_3_1; }
		
		//EBoolean
		public RuleCall getActiveEBooleanParserRuleCall_3_1_0() { return cActiveEBooleanParserRuleCall_3_1_0; }
		
		//('surname:' surname=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'surname:'
		public Keyword getSurnameKeyword_4_0() { return cSurnameKeyword_4_0; }
		
		//surname=EString
		public Assignment getSurnameAssignment_4_1() { return cSurnameAssignment_4_1; }
		
		//EString
		public RuleCall getSurnameEStringParserRuleCall_4_1_0() { return cSurnameEStringParserRuleCall_4_1_0; }
		
		//('username:' username=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'username:'
		public Keyword getUsernameKeyword_5_0() { return cUsernameKeyword_5_0; }
		
		//username=EString
		public Assignment getUsernameAssignment_5_1() { return cUsernameAssignment_5_1; }
		
		//EString
		public RuleCall getUsernameEStringParserRuleCall_5_1_0() { return cUsernameEStringParserRuleCall_5_1_0; }
		
		//('password:' password=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'password:'
		public Keyword getPasswordKeyword_6_0() { return cPasswordKeyword_6_0; }
		
		//password=EString
		public Assignment getPasswordAssignment_6_1() { return cPasswordAssignment_6_1; }
		
		//EString
		public RuleCall getPasswordEStringParserRuleCall_6_1_0() { return cPasswordEStringParserRuleCall_6_1_0; }
		
		//('email:' email=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'email:'
		public Keyword getEmailKeyword_7_0() { return cEmailKeyword_7_0; }
		
		//email=EString
		public Assignment getEmailAssignment_7_1() { return cEmailAssignment_7_1; }
		
		//EString
		public RuleCall getEmailEStringParserRuleCall_7_1_0() { return cEmailEStringParserRuleCall_7_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_8() { return cRightCurlyBracketKeyword_8; }
	}
	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//    'true' | 'false';
		@Override public ParserRule getRule() { return rule; }
		
		//'true' | 'false'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//'true'
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }
		
		//'false'
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}
	public class ProductElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.Product");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProductKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cAvailableKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cAvailableAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cAvailableEBooleanParserRuleCall_3_1_0 = (RuleCall)cAvailableAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cStockKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cStockAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cStockEIntParserRuleCall_4_1_0 = (RuleCall)cStockAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cHeightKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cHeightAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cHeightEFloatParserRuleCall_5_1_0 = (RuleCall)cHeightAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cWeightKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cWeightAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cWeightEFloatParserRuleCall_6_1_0 = (RuleCall)cWeightAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPriceKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPriceAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPriceEFloatParserRuleCall_7_1_0 = (RuleCall)cPriceAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cDescriptionKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cDescriptionAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cDescriptionEStringParserRuleCall_8_1_0 = (RuleCall)cDescriptionAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cImagesKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_9_1 = (Keyword)cGroup_9.eContents().get(1);
		private final Assignment cProduct_have_imagesAssignment_9_2 = (Assignment)cGroup_9.eContents().get(2);
		private final RuleCall cProduct_have_imagesProductImageParserRuleCall_9_2_0 = (RuleCall)cProduct_have_imagesAssignment_9_2.eContents().get(0);
		private final Group cGroup_9_3 = (Group)cGroup_9.eContents().get(3);
		private final Keyword cCommaKeyword_9_3_0 = (Keyword)cGroup_9_3.eContents().get(0);
		private final Assignment cProduct_have_imagesAssignment_9_3_1 = (Assignment)cGroup_9_3.eContents().get(1);
		private final RuleCall cProduct_have_imagesProductImageParserRuleCall_9_3_1_0 = (RuleCall)cProduct_have_imagesAssignment_9_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_9_4 = (Keyword)cGroup_9.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Product returns Product:
		//    'Product'
		//    name=EString
		//    '{'
		//        ('available:' available=EBoolean)
		//        ('stock:' stock=EInt)
		//        ('height:' height=EFloat)
		//        ('weight:' weight=EFloat)
		//        ('price:' price=EFloat)
		//        ('description:' description=EString)?
		//        ('images' '[' product_have_images+=ProductImage ( "," product_have_images+=ProductImage)* ']' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Product'
		//name=EString
		//'{'
		//    ('available:' available=EBoolean)
		//    ('stock:' stock=EInt)
		//    ('height:' height=EFloat)
		//    ('weight:' weight=EFloat)
		//    ('price:' price=EFloat)
		//    ('description:' description=EString)?
		//    ('images' '[' product_have_images+=ProductImage ( "," product_have_images+=ProductImage)* ']' )?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Product'
		public Keyword getProductKeyword_0() { return cProductKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('available:' available=EBoolean)
		public Group getGroup_3() { return cGroup_3; }
		
		//'available:'
		public Keyword getAvailableKeyword_3_0() { return cAvailableKeyword_3_0; }
		
		//available=EBoolean
		public Assignment getAvailableAssignment_3_1() { return cAvailableAssignment_3_1; }
		
		//EBoolean
		public RuleCall getAvailableEBooleanParserRuleCall_3_1_0() { return cAvailableEBooleanParserRuleCall_3_1_0; }
		
		//('stock:' stock=EInt)
		public Group getGroup_4() { return cGroup_4; }
		
		//'stock:'
		public Keyword getStockKeyword_4_0() { return cStockKeyword_4_0; }
		
		//stock=EInt
		public Assignment getStockAssignment_4_1() { return cStockAssignment_4_1; }
		
		//EInt
		public RuleCall getStockEIntParserRuleCall_4_1_0() { return cStockEIntParserRuleCall_4_1_0; }
		
		//('height:' height=EFloat)
		public Group getGroup_5() { return cGroup_5; }
		
		//'height:'
		public Keyword getHeightKeyword_5_0() { return cHeightKeyword_5_0; }
		
		//height=EFloat
		public Assignment getHeightAssignment_5_1() { return cHeightAssignment_5_1; }
		
		//EFloat
		public RuleCall getHeightEFloatParserRuleCall_5_1_0() { return cHeightEFloatParserRuleCall_5_1_0; }
		
		//('weight:' weight=EFloat)
		public Group getGroup_6() { return cGroup_6; }
		
		//'weight:'
		public Keyword getWeightKeyword_6_0() { return cWeightKeyword_6_0; }
		
		//weight=EFloat
		public Assignment getWeightAssignment_6_1() { return cWeightAssignment_6_1; }
		
		//EFloat
		public RuleCall getWeightEFloatParserRuleCall_6_1_0() { return cWeightEFloatParserRuleCall_6_1_0; }
		
		//('price:' price=EFloat)
		public Group getGroup_7() { return cGroup_7; }
		
		//'price:'
		public Keyword getPriceKeyword_7_0() { return cPriceKeyword_7_0; }
		
		//price=EFloat
		public Assignment getPriceAssignment_7_1() { return cPriceAssignment_7_1; }
		
		//EFloat
		public RuleCall getPriceEFloatParserRuleCall_7_1_0() { return cPriceEFloatParserRuleCall_7_1_0; }
		
		//('description:' description=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'description:'
		public Keyword getDescriptionKeyword_8_0() { return cDescriptionKeyword_8_0; }
		
		//description=EString
		public Assignment getDescriptionAssignment_8_1() { return cDescriptionAssignment_8_1; }
		
		//EString
		public RuleCall getDescriptionEStringParserRuleCall_8_1_0() { return cDescriptionEStringParserRuleCall_8_1_0; }
		
		//('images' '[' product_have_images+=ProductImage ( "," product_have_images+=ProductImage)* ']' )?
		public Group getGroup_9() { return cGroup_9; }
		
		//'images'
		public Keyword getImagesKeyword_9_0() { return cImagesKeyword_9_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_9_1() { return cLeftSquareBracketKeyword_9_1; }
		
		//product_have_images+=ProductImage
		public Assignment getProduct_have_imagesAssignment_9_2() { return cProduct_have_imagesAssignment_9_2; }
		
		//ProductImage
		public RuleCall getProduct_have_imagesProductImageParserRuleCall_9_2_0() { return cProduct_have_imagesProductImageParserRuleCall_9_2_0; }
		
		//( "," product_have_images+=ProductImage)*
		public Group getGroup_9_3() { return cGroup_9_3; }
		
		//","
		public Keyword getCommaKeyword_9_3_0() { return cCommaKeyword_9_3_0; }
		
		//product_have_images+=ProductImage
		public Assignment getProduct_have_imagesAssignment_9_3_1() { return cProduct_have_imagesAssignment_9_3_1; }
		
		//ProductImage
		public RuleCall getProduct_have_imagesProductImageParserRuleCall_9_3_1_0() { return cProduct_have_imagesProductImageParserRuleCall_9_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_9_4() { return cRightSquareBracketKeyword_9_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//    '-'? INT;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}
	public class EFloatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.EFloat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Alternatives cAlternatives_4_0 = (Alternatives)cGroup_4.eContents().get(0);
		private final Keyword cEKeyword_4_0_0 = (Keyword)cAlternatives_4_0.eContents().get(0);
		private final Keyword cEKeyword_4_0_1 = (Keyword)cAlternatives_4_0.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_4_2 = (RuleCall)cGroup_4.eContents().get(2);
		
		//EFloat returns ecore::EFloat:
		//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
		@Override public ParserRule getRule() { return rule; }
		
		//'-'? INT? '.' INT (('E'|'e') '-'? INT)?
		public Group getGroup() { return cGroup; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }
		
		//INT?
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
		
		//'.'
		public Keyword getFullStopKeyword_2() { return cFullStopKeyword_2; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_3() { return cINTTerminalRuleCall_3; }
		
		//(('E'|'e') '-'? INT)?
		public Group getGroup_4() { return cGroup_4; }
		
		//('E'|'e')
		public Alternatives getAlternatives_4_0() { return cAlternatives_4_0; }
		
		//'E'
		public Keyword getEKeyword_4_0_0() { return cEKeyword_4_0_0; }
		
		//'e'
		public Keyword getEKeyword_4_0_1() { return cEKeyword_4_0_1; }
		
		//'-'?
		public Keyword getHyphenMinusKeyword_4_1() { return cHyphenMinusKeyword_4_1; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_4_2() { return cINTTerminalRuleCall_4_2; }
	}
	public class ProductImageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.ProductImage");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProductImageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cRefKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cRefAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cRefEStringParserRuleCall_2_1_0 = (RuleCall)cRefAssignment_2_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//ProductImage returns ProductImage:
		//    'ProductImage'
		//    '{'
		//        ('ref' ref=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ProductImage'
		//'{'
		//    ('ref' ref=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ProductImage'
		public Keyword getProductImageKeyword_0() { return cProductImageKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('ref' ref=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'ref'
		public Keyword getRefKeyword_2_0() { return cRefKeyword_2_0; }
		
		//ref=EString
		public Assignment getRefAssignment_2_1() { return cRefAssignment_2_1; }
		
		//EString
		public RuleCall getRefEStringParserRuleCall_2_1_0() { return cRefEStringParserRuleCall_2_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}
	public class AddressElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.Address");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddressKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cActiveKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cActiveAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cActiveEBooleanParserRuleCall_3_1_0 = (RuleCall)cActiveAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCountryKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cCountryAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cCountryEStringParserRuleCall_4_1_0 = (RuleCall)cCountryAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cStateKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cStateAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cStateEStringParserRuleCall_5_1_0 = (RuleCall)cStateAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCityKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cCityAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cCityEStringParserRuleCall_6_1_0 = (RuleCall)cCityAssignment_6_1.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cPost_codeKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cPost_codeAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cPost_codeEStringParserRuleCall_7_1_0 = (RuleCall)cPost_codeAssignment_7_1.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cPhoneKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cPhoneAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cPhoneEStringParserRuleCall_8_1_0 = (RuleCall)cPhoneAssignment_8_1.eContents().get(0);
		private final Group cGroup_9 = (Group)cGroup.eContents().get(9);
		private final Keyword cStreet_addressKeyword_9_0 = (Keyword)cGroup_9.eContents().get(0);
		private final Assignment cStreet_addressAssignment_9_1 = (Assignment)cGroup_9.eContents().get(1);
		private final RuleCall cStreet_addressEStringParserRuleCall_9_1_0 = (RuleCall)cStreet_addressAssignment_9_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//Address returns Address:
		//    'Address'
		//    name=EString
		//    '{'
		//        ('active:' active=EBoolean)
		//        ('country:' country=EString)?
		//        ('state:' state=EString)?
		//        ('city:' city=EString)?
		//        ('post_code:' post_code=EString)?
		//        ('phone:' phone=EString)?
		//        ('street_address:' street_address=EString)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Address'
		//name=EString
		//'{'
		//    ('active:' active=EBoolean)
		//    ('country:' country=EString)?
		//    ('state:' state=EString)?
		//    ('city:' city=EString)?
		//    ('post_code:' post_code=EString)?
		//    ('phone:' phone=EString)?
		//    ('street_address:' street_address=EString)?
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Address'
		public Keyword getAddressKeyword_0() { return cAddressKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('active:' active=EBoolean)
		public Group getGroup_3() { return cGroup_3; }
		
		//'active:'
		public Keyword getActiveKeyword_3_0() { return cActiveKeyword_3_0; }
		
		//active=EBoolean
		public Assignment getActiveAssignment_3_1() { return cActiveAssignment_3_1; }
		
		//EBoolean
		public RuleCall getActiveEBooleanParserRuleCall_3_1_0() { return cActiveEBooleanParserRuleCall_3_1_0; }
		
		//('country:' country=EString)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'country:'
		public Keyword getCountryKeyword_4_0() { return cCountryKeyword_4_0; }
		
		//country=EString
		public Assignment getCountryAssignment_4_1() { return cCountryAssignment_4_1; }
		
		//EString
		public RuleCall getCountryEStringParserRuleCall_4_1_0() { return cCountryEStringParserRuleCall_4_1_0; }
		
		//('state:' state=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'state:'
		public Keyword getStateKeyword_5_0() { return cStateKeyword_5_0; }
		
		//state=EString
		public Assignment getStateAssignment_5_1() { return cStateAssignment_5_1; }
		
		//EString
		public RuleCall getStateEStringParserRuleCall_5_1_0() { return cStateEStringParserRuleCall_5_1_0; }
		
		//('city:' city=EString)?
		public Group getGroup_6() { return cGroup_6; }
		
		//'city:'
		public Keyword getCityKeyword_6_0() { return cCityKeyword_6_0; }
		
		//city=EString
		public Assignment getCityAssignment_6_1() { return cCityAssignment_6_1; }
		
		//EString
		public RuleCall getCityEStringParserRuleCall_6_1_0() { return cCityEStringParserRuleCall_6_1_0; }
		
		//('post_code:' post_code=EString)?
		public Group getGroup_7() { return cGroup_7; }
		
		//'post_code:'
		public Keyword getPost_codeKeyword_7_0() { return cPost_codeKeyword_7_0; }
		
		//post_code=EString
		public Assignment getPost_codeAssignment_7_1() { return cPost_codeAssignment_7_1; }
		
		//EString
		public RuleCall getPost_codeEStringParserRuleCall_7_1_0() { return cPost_codeEStringParserRuleCall_7_1_0; }
		
		//('phone:' phone=EString)?
		public Group getGroup_8() { return cGroup_8; }
		
		//'phone:'
		public Keyword getPhoneKeyword_8_0() { return cPhoneKeyword_8_0; }
		
		//phone=EString
		public Assignment getPhoneAssignment_8_1() { return cPhoneAssignment_8_1; }
		
		//EString
		public RuleCall getPhoneEStringParserRuleCall_8_1_0() { return cPhoneEStringParserRuleCall_8_1_0; }
		
		//('street_address:' street_address=EString)?
		public Group getGroup_9() { return cGroup_9; }
		
		//'street_address:'
		public Keyword getStreet_addressKeyword_9_0() { return cStreet_addressKeyword_9_0; }
		
		//street_address=EString
		public Assignment getStreet_addressAssignment_9_1() { return cStreet_addressAssignment_9_1; }
		
		//EString
		public RuleCall getStreet_addressEStringParserRuleCall_9_1_0() { return cStreet_addressEStringParserRuleCall_9_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}
	public class CartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.Cart");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDate_addedKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDate_addedAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDate_addedEDateParserRuleCall_3_1_0 = (RuleCall)cDate_addedAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cCart_itemsKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_4_1 = (Keyword)cGroup_4.eContents().get(1);
		private final Assignment cCart_have_itemsAssignment_4_2 = (Assignment)cGroup_4.eContents().get(2);
		private final RuleCall cCart_have_itemsItemCartParserRuleCall_4_2_0 = (RuleCall)cCart_have_itemsAssignment_4_2.eContents().get(0);
		private final Group cGroup_4_3 = (Group)cGroup_4.eContents().get(3);
		private final Keyword cCommaKeyword_4_3_0 = (Keyword)cGroup_4_3.eContents().get(0);
		private final Assignment cCart_have_itemsAssignment_4_3_1 = (Assignment)cGroup_4_3.eContents().get(1);
		private final RuleCall cCart_have_itemsItemCartParserRuleCall_4_3_1_0 = (RuleCall)cCart_have_itemsAssignment_4_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4_4 = (Keyword)cGroup_4.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Cart returns Cart:
		//    'Cart'
		//    name=EString
		//    '{'
		//        ('date_added:' date_added=EDate)?
		//        ('cart_items:' '{' cart_have_items+=ItemCart ( "," cart_have_items+=ItemCart)* '}' )?
		////        ('cart_order:' cart_have_order=Order)?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//    'Cart'
		//    name=EString
		//    '{'
		//        ('date_added:' date_added=EDate)?
		//        ('cart_items:' '{' cart_have_items+=ItemCart ( "," cart_have_items+=ItemCart)* '}' )?
		////        ('cart_order:' cart_have_order=Order)?
		//    '}'
		public Group getGroup() { return cGroup; }
		
		//'Cart'
		public Keyword getCartKeyword_0() { return cCartKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('date_added:' date_added=EDate)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'date_added:'
		public Keyword getDate_addedKeyword_3_0() { return cDate_addedKeyword_3_0; }
		
		//date_added=EDate
		public Assignment getDate_addedAssignment_3_1() { return cDate_addedAssignment_3_1; }
		
		//EDate
		public RuleCall getDate_addedEDateParserRuleCall_3_1_0() { return cDate_addedEDateParserRuleCall_3_1_0; }
		
		//('cart_items:' '{' cart_have_items+=ItemCart ( "," cart_have_items+=ItemCart)* '}' )?
		public Group getGroup_4() { return cGroup_4; }
		
		//'cart_items:'
		public Keyword getCart_itemsKeyword_4_0() { return cCart_itemsKeyword_4_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_4_1() { return cLeftCurlyBracketKeyword_4_1; }
		
		//cart_have_items+=ItemCart
		public Assignment getCart_have_itemsAssignment_4_2() { return cCart_have_itemsAssignment_4_2; }
		
		//ItemCart
		public RuleCall getCart_have_itemsItemCartParserRuleCall_4_2_0() { return cCart_have_itemsItemCartParserRuleCall_4_2_0; }
		
		//( "," cart_have_items+=ItemCart)*
		public Group getGroup_4_3() { return cGroup_4_3; }
		
		//","
		public Keyword getCommaKeyword_4_3_0() { return cCommaKeyword_4_3_0; }
		
		//cart_have_items+=ItemCart
		public Assignment getCart_have_itemsAssignment_4_3_1() { return cCart_have_itemsAssignment_4_3_1; }
		
		//ItemCart
		public RuleCall getCart_have_itemsItemCartParserRuleCall_4_3_1_0() { return cCart_have_itemsItemCartParserRuleCall_4_3_1_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_4_4() { return cRightCurlyBracketKeyword_4_4; }
		
		////        ('cart_order:' cart_have_order=Order)?
		//    '}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class EDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.EDate");
		private final Keyword cEDateKeyword = (Keyword)rule.eContents().get(1);
		
		//EDate returns ecore::EDate:
		//    'EDate' /* TODO: implement this rule and an appropriate IValueConverter */;
		@Override public ParserRule getRule() { return rule; }
		
		//'EDate'
		public Keyword getEDateKeyword() { return cEDateKeyword; }
	}
	public class ItemCartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.ItemCart");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cItemCartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cQuantityKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cQuantityAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cQuantityEIntParserRuleCall_3_1_0 = (RuleCall)cQuantityAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cProductKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cItem_cart_have_productAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final CrossReference cItem_cart_have_productProductCrossReference_4_1_0 = (CrossReference)cItem_cart_have_productAssignment_4_1.eContents().get(0);
		private final RuleCall cItem_cart_have_productProductEStringParserRuleCall_4_1_0_1 = (RuleCall)cItem_cart_have_productProductCrossReference_4_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//ItemCart returns ItemCart:
		//    'ItemCart'
		//    name=EString
		//    '{'
		//        ('quantity' quantity=EInt)
		//        ('product' item_cart_have_product=[Product|EString])
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'ItemCart'
		//name=EString
		//'{'
		//    ('quantity' quantity=EInt)
		//    ('product' item_cart_have_product=[Product|EString])
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'ItemCart'
		public Keyword getItemCartKeyword_0() { return cItemCartKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('quantity' quantity=EInt)
		public Group getGroup_3() { return cGroup_3; }
		
		//'quantity'
		public Keyword getQuantityKeyword_3_0() { return cQuantityKeyword_3_0; }
		
		//quantity=EInt
		public Assignment getQuantityAssignment_3_1() { return cQuantityAssignment_3_1; }
		
		//EInt
		public RuleCall getQuantityEIntParserRuleCall_3_1_0() { return cQuantityEIntParserRuleCall_3_1_0; }
		
		//('product' item_cart_have_product=[Product|EString])
		public Group getGroup_4() { return cGroup_4; }
		
		//'product'
		public Keyword getProductKeyword_4_0() { return cProductKeyword_4_0; }
		
		//item_cart_have_product=[Product|EString]
		public Assignment getItem_cart_have_productAssignment_4_1() { return cItem_cart_have_productAssignment_4_1; }
		
		//[Product|EString]
		public CrossReference getItem_cart_have_productProductCrossReference_4_1_0() { return cItem_cart_have_productProductCrossReference_4_1_0; }
		
		//EString
		public RuleCall getItem_cart_have_productProductEStringParserRuleCall_4_1_0_1() { return cItem_cart_have_productProductEStringParserRuleCall_4_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class OrderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.Order");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cOrderKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cReference_numberKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cReference_numberAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cReference_numberEStringParserRuleCall_2_1_0 = (RuleCall)cReference_numberAssignment_2_1.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDate_createdKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDate_createdAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDate_createdEDateParserRuleCall_3_1_0 = (RuleCall)cDate_createdAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOrder_stateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOrder_stateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cOrder_stateOrderStateEnumRuleCall_4_1_0 = (RuleCall)cOrder_stateAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cInvoiceKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cOrder_has_invoiceAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cOrder_has_invoiceInvoiceParserRuleCall_5_1_0 = (RuleCall)cOrder_has_invoiceAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cShipmentsKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_6_1 = (Keyword)cGroup_6.eContents().get(1);
		private final Assignment cOrder_have_shipmentAssignment_6_2 = (Assignment)cGroup_6.eContents().get(2);
		private final RuleCall cOrder_have_shipmentShipmentParserRuleCall_6_2_0 = (RuleCall)cOrder_have_shipmentAssignment_6_2.eContents().get(0);
		private final Group cGroup_6_3 = (Group)cGroup_6.eContents().get(3);
		private final Keyword cCommaKeyword_6_3_0 = (Keyword)cGroup_6_3.eContents().get(0);
		private final Assignment cOrder_have_shipmentAssignment_6_3_1 = (Assignment)cGroup_6_3.eContents().get(1);
		private final RuleCall cOrder_have_shipmentShipmentParserRuleCall_6_3_1_0 = (RuleCall)cOrder_have_shipmentAssignment_6_3_1.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_6_4 = (Keyword)cGroup_6.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Order returns Order:
		//    'Order'
		//    '{'
		//        ('reference_number:' reference_number=EString)?
		//        ('date_created:' date_created=EDate)?
		//        ('order_state:' order_state=OrderState)?
		////        ('order_for_cart:' order_for_cart=[Cart|EString])
		//        ('invoice:' order_has_invoice=Invoice)?
		//        ('shipments:' '[' order_have_shipment+=Shipment ( "," order_have_shipment+=Shipment)* ']' )?
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//    'Order'
		//    '{'
		//        ('reference_number:' reference_number=EString)?
		//        ('date_created:' date_created=EDate)?
		//        ('order_state:' order_state=OrderState)?
		////        ('order_for_cart:' order_for_cart=[Cart|EString])
		//        ('invoice:' order_has_invoice=Invoice)?
		//        ('shipments:' '[' order_have_shipment+=Shipment ( "," order_have_shipment+=Shipment)* ']' )?
		//    '}'
		public Group getGroup() { return cGroup; }
		
		//'Order'
		public Keyword getOrderKeyword_0() { return cOrderKeyword_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }
		
		//('reference_number:' reference_number=EString)?
		public Group getGroup_2() { return cGroup_2; }
		
		//'reference_number:'
		public Keyword getReference_numberKeyword_2_0() { return cReference_numberKeyword_2_0; }
		
		//reference_number=EString
		public Assignment getReference_numberAssignment_2_1() { return cReference_numberAssignment_2_1; }
		
		//EString
		public RuleCall getReference_numberEStringParserRuleCall_2_1_0() { return cReference_numberEStringParserRuleCall_2_1_0; }
		
		//('date_created:' date_created=EDate)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'date_created:'
		public Keyword getDate_createdKeyword_3_0() { return cDate_createdKeyword_3_0; }
		
		//date_created=EDate
		public Assignment getDate_createdAssignment_3_1() { return cDate_createdAssignment_3_1; }
		
		//EDate
		public RuleCall getDate_createdEDateParserRuleCall_3_1_0() { return cDate_createdEDateParserRuleCall_3_1_0; }
		
		//('order_state:' order_state=OrderState)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'order_state:'
		public Keyword getOrder_stateKeyword_4_0() { return cOrder_stateKeyword_4_0; }
		
		//order_state=OrderState
		public Assignment getOrder_stateAssignment_4_1() { return cOrder_stateAssignment_4_1; }
		
		//OrderState
		public RuleCall getOrder_stateOrderStateEnumRuleCall_4_1_0() { return cOrder_stateOrderStateEnumRuleCall_4_1_0; }
		
		////        ('order_for_cart:' order_for_cart=[Cart|EString])
		//        ('invoice:' order_has_invoice=Invoice)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'invoice:'
		public Keyword getInvoiceKeyword_5_0() { return cInvoiceKeyword_5_0; }
		
		//order_has_invoice=Invoice
		public Assignment getOrder_has_invoiceAssignment_5_1() { return cOrder_has_invoiceAssignment_5_1; }
		
		//Invoice
		public RuleCall getOrder_has_invoiceInvoiceParserRuleCall_5_1_0() { return cOrder_has_invoiceInvoiceParserRuleCall_5_1_0; }
		
		//('shipments:' '[' order_have_shipment+=Shipment ( "," order_have_shipment+=Shipment)* ']' )?
		public Group getGroup_6() { return cGroup_6; }
		
		//'shipments:'
		public Keyword getShipmentsKeyword_6_0() { return cShipmentsKeyword_6_0; }
		
		//'['
		public Keyword getLeftSquareBracketKeyword_6_1() { return cLeftSquareBracketKeyword_6_1; }
		
		//order_have_shipment+=Shipment
		public Assignment getOrder_have_shipmentAssignment_6_2() { return cOrder_have_shipmentAssignment_6_2; }
		
		//Shipment
		public RuleCall getOrder_have_shipmentShipmentParserRuleCall_6_2_0() { return cOrder_have_shipmentShipmentParserRuleCall_6_2_0; }
		
		//( "," order_have_shipment+=Shipment)*
		public Group getGroup_6_3() { return cGroup_6_3; }
		
		//","
		public Keyword getCommaKeyword_6_3_0() { return cCommaKeyword_6_3_0; }
		
		//order_have_shipment+=Shipment
		public Assignment getOrder_have_shipmentAssignment_6_3_1() { return cOrder_have_shipmentAssignment_6_3_1; }
		
		//Shipment
		public RuleCall getOrder_have_shipmentShipmentParserRuleCall_6_3_1_0() { return cOrder_have_shipmentShipmentParserRuleCall_6_3_1_0; }
		
		//']'
		public Keyword getRightSquareBracketKeyword_6_4() { return cRightSquareBracketKeyword_6_4; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	public class InvoiceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.Invoice");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInvoiceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cInvoice_idKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cInvoice_idAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cInvoice_idEIntParserRuleCall_3_1_0 = (RuleCall)cInvoice_idAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDateEDateParserRuleCall_4_1_0 = (RuleCall)cDateAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//Invoice returns Invoice:
		//    'Invoice'
		//    name=EString
		//    '{'
		//        ('invoice_id:' invoice_id=EInt)
		//        ('date:' date=EDate)?
		////        ('invoice_for_order:' invoice_for_order=[Order|EString])
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//    'Invoice'
		//    name=EString
		//    '{'
		//        ('invoice_id:' invoice_id=EInt)
		//        ('date:' date=EDate)?
		////        ('invoice_for_order:' invoice_for_order=[Order|EString])
		//    '}'
		public Group getGroup() { return cGroup; }
		
		//'Invoice'
		public Keyword getInvoiceKeyword_0() { return cInvoiceKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('invoice_id:' invoice_id=EInt)
		public Group getGroup_3() { return cGroup_3; }
		
		//'invoice_id:'
		public Keyword getInvoice_idKeyword_3_0() { return cInvoice_idKeyword_3_0; }
		
		//invoice_id=EInt
		public Assignment getInvoice_idAssignment_3_1() { return cInvoice_idAssignment_3_1; }
		
		//EInt
		public RuleCall getInvoice_idEIntParserRuleCall_3_1_0() { return cInvoice_idEIntParserRuleCall_3_1_0; }
		
		//('date:' date=EDate)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'date:'
		public Keyword getDateKeyword_4_0() { return cDateKeyword_4_0; }
		
		//date=EDate
		public Assignment getDateAssignment_4_1() { return cDateAssignment_4_1; }
		
		//EDate
		public RuleCall getDateEDateParserRuleCall_4_1_0() { return cDateEDateParserRuleCall_4_1_0; }
		
		////        ('invoice_for_order:' invoice_for_order=[Order|EString])
		//    '}'
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}
	public class ShipmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.Shipment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cShipmentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cShipment_statusKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cShipment_statusAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cShipment_statusShipmentStatusEnumRuleCall_3_1_0 = (RuleCall)cShipment_statusAssignment_3_1.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cDateKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cDateAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cDateEDateParserRuleCall_4_1_0 = (RuleCall)cDateAssignment_4_1.eContents().get(0);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cShipment_noKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cShipment_noAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final RuleCall cShipment_noEStringParserRuleCall_5_1_0 = (RuleCall)cShipment_noAssignment_5_1.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cShipment_addressKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cShipment_has_addressAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final CrossReference cShipment_has_addressAddressCrossReference_6_1_0 = (CrossReference)cShipment_has_addressAssignment_6_1.eContents().get(0);
		private final RuleCall cShipment_has_addressAddressEStringParserRuleCall_6_1_0_1 = (RuleCall)cShipment_has_addressAddressCrossReference_6_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Shipment returns Shipment:
		//    'Shipment'
		//    name=EString
		//    '{'
		//        ('shipment_status:' shipment_status=ShipmentStatus)?
		//        ('date:' date=EDate)?
		//        ('shipment_no:' shipment_no=EString)?
		//        ('shipment_address:' shipment_has_address=[Address|EString])
		//    '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'Shipment'
		//name=EString
		//'{'
		//    ('shipment_status:' shipment_status=ShipmentStatus)?
		//    ('date:' date=EDate)?
		//    ('shipment_no:' shipment_no=EString)?
		//    ('shipment_address:' shipment_has_address=[Address|EString])
		//'}'
		public Group getGroup() { return cGroup; }
		
		//'Shipment'
		public Keyword getShipmentKeyword_0() { return cShipmentKeyword_0; }
		
		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }
		
		//('shipment_status:' shipment_status=ShipmentStatus)?
		public Group getGroup_3() { return cGroup_3; }
		
		//'shipment_status:'
		public Keyword getShipment_statusKeyword_3_0() { return cShipment_statusKeyword_3_0; }
		
		//shipment_status=ShipmentStatus
		public Assignment getShipment_statusAssignment_3_1() { return cShipment_statusAssignment_3_1; }
		
		//ShipmentStatus
		public RuleCall getShipment_statusShipmentStatusEnumRuleCall_3_1_0() { return cShipment_statusShipmentStatusEnumRuleCall_3_1_0; }
		
		//('date:' date=EDate)?
		public Group getGroup_4() { return cGroup_4; }
		
		//'date:'
		public Keyword getDateKeyword_4_0() { return cDateKeyword_4_0; }
		
		//date=EDate
		public Assignment getDateAssignment_4_1() { return cDateAssignment_4_1; }
		
		//EDate
		public RuleCall getDateEDateParserRuleCall_4_1_0() { return cDateEDateParserRuleCall_4_1_0; }
		
		//('shipment_no:' shipment_no=EString)?
		public Group getGroup_5() { return cGroup_5; }
		
		//'shipment_no:'
		public Keyword getShipment_noKeyword_5_0() { return cShipment_noKeyword_5_0; }
		
		//shipment_no=EString
		public Assignment getShipment_noAssignment_5_1() { return cShipment_noAssignment_5_1; }
		
		//EString
		public RuleCall getShipment_noEStringParserRuleCall_5_1_0() { return cShipment_noEStringParserRuleCall_5_1_0; }
		
		//('shipment_address:' shipment_has_address=[Address|EString])
		public Group getGroup_6() { return cGroup_6; }
		
		//'shipment_address:'
		public Keyword getShipment_addressKeyword_6_0() { return cShipment_addressKeyword_6_0; }
		
		//shipment_has_address=[Address|EString]
		public Assignment getShipment_has_addressAssignment_6_1() { return cShipment_has_addressAssignment_6_1; }
		
		//[Address|EString]
		public CrossReference getShipment_has_addressAddressCrossReference_6_1_0() { return cShipment_has_addressAddressCrossReference_6_1_0; }
		
		//EString
		public RuleCall getShipment_has_addressAddressEStringParserRuleCall_6_1_0_1() { return cShipment_has_addressAddressEStringParserRuleCall_6_1_0_1; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	public class OrderStateElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.OrderState");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPAIDEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPAIDPAIDKeyword_0_0 = (Keyword)cPAIDEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCOMMITTEDEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCOMMITTEDCOMMITTEDKeyword_1_0 = (Keyword)cCOMMITTEDEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cUNPAIDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cUNPAIDUNPAIDKeyword_2_0 = (Keyword)cUNPAIDEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum OrderState returns OrderState:
		//                PAID = 'PAID' | COMMITTED = 'COMMITTED' | UNPAID = 'UNPAID';
		public EnumRule getRule() { return rule; }
		
		//PAID = 'PAID' | COMMITTED = 'COMMITTED' | UNPAID = 'UNPAID'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PAID = 'PAID'
		public EnumLiteralDeclaration getPAIDEnumLiteralDeclaration_0() { return cPAIDEnumLiteralDeclaration_0; }
		
		//'PAID'
		public Keyword getPAIDPAIDKeyword_0_0() { return cPAIDPAIDKeyword_0_0; }
		
		//COMMITTED = 'COMMITTED'
		public EnumLiteralDeclaration getCOMMITTEDEnumLiteralDeclaration_1() { return cCOMMITTEDEnumLiteralDeclaration_1; }
		
		//'COMMITTED'
		public Keyword getCOMMITTEDCOMMITTEDKeyword_1_0() { return cCOMMITTEDCOMMITTEDKeyword_1_0; }
		
		//UNPAID = 'UNPAID'
		public EnumLiteralDeclaration getUNPAIDEnumLiteralDeclaration_2() { return cUNPAIDEnumLiteralDeclaration_2; }
		
		//'UNPAID'
		public Keyword getUNPAIDUNPAIDKeyword_2_0() { return cUNPAIDUNPAIDKeyword_2_0; }
	}
	public class ShipmentStatusElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "it.disim.univaq.ecommerce.xtext.Ecommerce.ShipmentStatus");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cPENDINGEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cPENDINGPENDINGKeyword_0_0 = (Keyword)cPENDINGEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cTRAVELINGEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cTRAVELINGTRAVELINGKeyword_1_0 = (Keyword)cTRAVELINGEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cDELIVEREDEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cDELIVEREDDELIVEREDKeyword_2_0 = (Keyword)cDELIVEREDEnumLiteralDeclaration_2.eContents().get(0);
		
		//enum ShipmentStatus returns ShipmentStatus:
		//                PENDING = 'PENDING' | TRAVELING = 'TRAVELING' | DELIVERED = 'DELIVERED';
		public EnumRule getRule() { return rule; }
		
		//PENDING = 'PENDING' | TRAVELING = 'TRAVELING' | DELIVERED = 'DELIVERED'
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//PENDING = 'PENDING'
		public EnumLiteralDeclaration getPENDINGEnumLiteralDeclaration_0() { return cPENDINGEnumLiteralDeclaration_0; }
		
		//'PENDING'
		public Keyword getPENDINGPENDINGKeyword_0_0() { return cPENDINGPENDINGKeyword_0_0; }
		
		//TRAVELING = 'TRAVELING'
		public EnumLiteralDeclaration getTRAVELINGEnumLiteralDeclaration_1() { return cTRAVELINGEnumLiteralDeclaration_1; }
		
		//'TRAVELING'
		public Keyword getTRAVELINGTRAVELINGKeyword_1_0() { return cTRAVELINGTRAVELINGKeyword_1_0; }
		
		//DELIVERED = 'DELIVERED'
		public EnumLiteralDeclaration getDELIVEREDEnumLiteralDeclaration_2() { return cDELIVEREDEnumLiteralDeclaration_2; }
		
		//'DELIVERED'
		public Keyword getDELIVEREDDELIVEREDKeyword_2_0() { return cDELIVEREDDELIVEREDKeyword_2_0; }
	}
	
	private final EcommerceSystemElements pEcommerceSystem;
	private final EStringElements pEString;
	private final CategoryElements pCategory;
	private final CustomerElements pCustomer;
	private final AdministratorElements pAdministrator;
	private final EBooleanElements pEBoolean;
	private final ProductElements pProduct;
	private final EIntElements pEInt;
	private final EFloatElements pEFloat;
	private final ProductImageElements pProductImage;
	private final AddressElements pAddress;
	private final CartElements pCart;
	private final EDateElements pEDate;
	private final ItemCartElements pItemCart;
	private final OrderElements pOrder;
	private final OrderStateElements eOrderState;
	private final InvoiceElements pInvoice;
	private final ShipmentElements pShipment;
	private final ShipmentStatusElements eShipmentStatus;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public EcommerceGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pEcommerceSystem = new EcommerceSystemElements();
		this.pEString = new EStringElements();
		this.pCategory = new CategoryElements();
		this.pCustomer = new CustomerElements();
		this.pAdministrator = new AdministratorElements();
		this.pEBoolean = new EBooleanElements();
		this.pProduct = new ProductElements();
		this.pEInt = new EIntElements();
		this.pEFloat = new EFloatElements();
		this.pProductImage = new ProductImageElements();
		this.pAddress = new AddressElements();
		this.pCart = new CartElements();
		this.pEDate = new EDateElements();
		this.pItemCart = new ItemCartElements();
		this.pOrder = new OrderElements();
		this.eOrderState = new OrderStateElements();
		this.pInvoice = new InvoiceElements();
		this.pShipment = new ShipmentElements();
		this.eShipmentStatus = new ShipmentStatusElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("it.disim.univaq.ecommerce.xtext.Ecommerce".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//EcommerceSystem returns EcommerceSystem:
	//    'EcommerceSystem'
	//    name=EString
	//    '{'
	//        ('categories' '[' shop_have_categories+=Category ( "," shop_have_categories+=Category)* ']' )?
	//        ('customers' '[' have_clients+=Customer ( "," have_clients+=Customer)* ']' )?
	//        ('administrators' '[' shop_have_administrators+=Administrator ( "," shop_have_administrators+=Administrator)* ']' )?
	//    '}';
	public EcommerceSystemElements getEcommerceSystemAccess() {
		return pEcommerceSystem;
	}
	
	public ParserRule getEcommerceSystemRule() {
		return getEcommerceSystemAccess().getRule();
	}
	
	//EString returns ecore::EString:
	//    STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}
	
	//Category returns Category:
	//    'Category'
	//    name=EString
	//    '{'
	//        ('active:' active=EBoolean)
	//        ('root_cat:' root_cat=EBoolean)
	//        ('sub_categories' '[' have_sub_categories+=Category ( "," have_sub_categories+=Category)* ']' )?
	//        ('products' '[' have_products+=Product ( "," have_products+=Product)* ']' )?
	//    '}';
	public CategoryElements getCategoryAccess() {
		return pCategory;
	}
	
	public ParserRule getCategoryRule() {
		return getCategoryAccess().getRule();
	}
	
	//Customer returns Customer:
	//    'Customer'
	//    name=EString
	//    '{'
	//        ('active:' active=EBoolean)
	//        ('surname:' surname=EString)?
	//        ('username:' username=EString)?
	//        ('password:' password=EString)?
	//        ('email:' email=EString)?
	//        ('address' '{' customer_have_address+=Address ( "," customer_have_address+=Address)* '}' )
	//        ('cart' '{' customer_have_cart=Cart '}')?
	//    '}';
	public CustomerElements getCustomerAccess() {
		return pCustomer;
	}
	
	public ParserRule getCustomerRule() {
		return getCustomerAccess().getRule();
	}
	
	//Administrator returns Administrator:
	//    'Administrator'
	//    name=EString
	//    '{'
	//        ('active:' active=EBoolean)
	//        ('surname:' surname=EString)?
	//        ('username:' username=EString)?
	//        ('password:' password=EString)?
	//        ('email:' email=EString)?
	//    '}';
	public AdministratorElements getAdministratorAccess() {
		return pAdministrator;
	}
	
	public ParserRule getAdministratorRule() {
		return getAdministratorAccess().getRule();
	}
	
	//EBoolean returns ecore::EBoolean:
	//    'true' | 'false';
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}
	
	//Product returns Product:
	//    'Product'
	//    name=EString
	//    '{'
	//        ('available:' available=EBoolean)
	//        ('stock:' stock=EInt)
	//        ('height:' height=EFloat)
	//        ('weight:' weight=EFloat)
	//        ('price:' price=EFloat)
	//        ('description:' description=EString)?
	//        ('images' '[' product_have_images+=ProductImage ( "," product_have_images+=ProductImage)* ']' )?
	//    '}';
	public ProductElements getProductAccess() {
		return pProduct;
	}
	
	public ParserRule getProductRule() {
		return getProductAccess().getRule();
	}
	
	//EInt returns ecore::EInt:
	//    '-'? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}
	
	//EFloat returns ecore::EFloat:
	//    '-'? INT? '.' INT (('E'|'e') '-'? INT)?;
	public EFloatElements getEFloatAccess() {
		return pEFloat;
	}
	
	public ParserRule getEFloatRule() {
		return getEFloatAccess().getRule();
	}
	
	//ProductImage returns ProductImage:
	//    'ProductImage'
	//    '{'
	//        ('ref' ref=EString)?
	//    '}';
	public ProductImageElements getProductImageAccess() {
		return pProductImage;
	}
	
	public ParserRule getProductImageRule() {
		return getProductImageAccess().getRule();
	}
	
	//Address returns Address:
	//    'Address'
	//    name=EString
	//    '{'
	//        ('active:' active=EBoolean)
	//        ('country:' country=EString)?
	//        ('state:' state=EString)?
	//        ('city:' city=EString)?
	//        ('post_code:' post_code=EString)?
	//        ('phone:' phone=EString)?
	//        ('street_address:' street_address=EString)?
	//    '}';
	public AddressElements getAddressAccess() {
		return pAddress;
	}
	
	public ParserRule getAddressRule() {
		return getAddressAccess().getRule();
	}
	
	//Cart returns Cart:
	//    'Cart'
	//    name=EString
	//    '{'
	//        ('date_added:' date_added=EDate)?
	//        ('cart_items:' '{' cart_have_items+=ItemCart ( "," cart_have_items+=ItemCart)* '}' )?
	////        ('cart_order:' cart_have_order=Order)?
	//    '}';
	public CartElements getCartAccess() {
		return pCart;
	}
	
	public ParserRule getCartRule() {
		return getCartAccess().getRule();
	}
	
	//EDate returns ecore::EDate:
	//    'EDate' /* TODO: implement this rule and an appropriate IValueConverter */;
	public EDateElements getEDateAccess() {
		return pEDate;
	}
	
	public ParserRule getEDateRule() {
		return getEDateAccess().getRule();
	}
	
	//ItemCart returns ItemCart:
	//    'ItemCart'
	//    name=EString
	//    '{'
	//        ('quantity' quantity=EInt)
	//        ('product' item_cart_have_product=[Product|EString])
	//    '}';
	public ItemCartElements getItemCartAccess() {
		return pItemCart;
	}
	
	public ParserRule getItemCartRule() {
		return getItemCartAccess().getRule();
	}
	
	//Order returns Order:
	//    'Order'
	//    '{'
	//        ('reference_number:' reference_number=EString)?
	//        ('date_created:' date_created=EDate)?
	//        ('order_state:' order_state=OrderState)?
	////        ('order_for_cart:' order_for_cart=[Cart|EString])
	//        ('invoice:' order_has_invoice=Invoice)?
	//        ('shipments:' '[' order_have_shipment+=Shipment ( "," order_have_shipment+=Shipment)* ']' )?
	//    '}';
	public OrderElements getOrderAccess() {
		return pOrder;
	}
	
	public ParserRule getOrderRule() {
		return getOrderAccess().getRule();
	}
	
	//enum OrderState returns OrderState:
	//                PAID = 'PAID' | COMMITTED = 'COMMITTED' | UNPAID = 'UNPAID';
	public OrderStateElements getOrderStateAccess() {
		return eOrderState;
	}
	
	public EnumRule getOrderStateRule() {
		return getOrderStateAccess().getRule();
	}
	
	//Invoice returns Invoice:
	//    'Invoice'
	//    name=EString
	//    '{'
	//        ('invoice_id:' invoice_id=EInt)
	//        ('date:' date=EDate)?
	////        ('invoice_for_order:' invoice_for_order=[Order|EString])
	//    '}';
	public InvoiceElements getInvoiceAccess() {
		return pInvoice;
	}
	
	public ParserRule getInvoiceRule() {
		return getInvoiceAccess().getRule();
	}
	
	//Shipment returns Shipment:
	//    'Shipment'
	//    name=EString
	//    '{'
	//        ('shipment_status:' shipment_status=ShipmentStatus)?
	//        ('date:' date=EDate)?
	//        ('shipment_no:' shipment_no=EString)?
	//        ('shipment_address:' shipment_has_address=[Address|EString])
	//    '}';
	public ShipmentElements getShipmentAccess() {
		return pShipment;
	}
	
	public ParserRule getShipmentRule() {
		return getShipmentAccess().getRule();
	}
	
	//enum ShipmentStatus returns ShipmentStatus:
	//                PENDING = 'PENDING' | TRAVELING = 'TRAVELING' | DELIVERED = 'DELIVERED';
	public ShipmentStatusElements getShipmentStatusAccess() {
		return eShipmentStatus;
	}
	
	public EnumRule getShipmentStatusRule() {
		return getShipmentStatusAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
