/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.ecommerce.xtext.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import it.disim.univaq.ecommerce.xtext.EcommerceRuntimeModule;
import it.disim.univaq.ecommerce.xtext.EcommerceStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class EcommerceIdeSetup extends EcommerceStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new EcommerceRuntimeModule(), new EcommerceIdeModule()));
	}
	
}
