/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.ecommerce.xtext.ide;


/**
 * Use this class to register ide components.
 */
public class EcommerceIdeModule extends AbstractEcommerceIdeModule {
}
