/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.ecommerce.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EcommerceUiModule extends AbstractEcommerceUiModule {

	public EcommerceUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
