/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.ecommerce.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractEcommerceScopeProvider extends DelegatingScopeProvider {
}
