/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.ecommerce.xtext.ui.tests;

import com.google.inject.Injector;
import it.disim.univaq.ecommerce.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class EcommerceUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return XtextActivator.getInstance().getInjector("it.disim.univaq.ecommerce.xtext.Ecommerce");
	}

}
