package ECOMML.constraints;

/*Generated by MPS */

import jetbrains.mps.core.aspects.constraints.rules.BaseRulesConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.constraints.rules.Rule;
import jetbrains.mps.core.aspects.constraints.rules.kinds.ContainmentContext;
import java.util.List;
import java.util.Collections;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.core.aspects.constraints.rules.BaseRule;
import org.jetbrains.mps.openapi.model.SNodeReference;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;
import jetbrains.mps.core.aspects.constraints.rules.RuleId;
import jetbrains.mps.core.aspects.constraints.rules.kinds.PredefinedRuleKinds;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import org.jetbrains.mps.openapi.language.SProperty;

public final class Administrator_ConstraintRules extends BaseRulesConstraintsDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xec1bc844bf74e86L, 0x9b15a8f6767d0e4eL, 0x15d9852c2ef0a049L, "ECOMML.structure.Administrator");

  public static final Rule<ContainmentContext> check_id8350359768424801452 = new Rule_EmailValidation();
  public static final Rule<ContainmentContext> check_id8350359768424801467 = new Rule_UsernameValidation();

  private static final List<Rule<?>> RULES = Collections.unmodifiableList(Arrays.<Rule<?>>asList(check_id8350359768424801452, check_id8350359768424801467));

  @NotNull
  @Override
  public List<Rule<?>> getDeclaredRules() {
    return RULES;
  }

  public static final class Rule_EmailValidation extends BaseRule<ContainmentContext> {
    private static final SNodeReference SOURCE_NODE_REF = PersistenceFacade.getInstance().createNodeReference("r:e37bf0b8-68b1-4e87-8693-247fc650f609(ECOMML.constraints)/8350359768424801452");
    public static final RuleId ID_EmailValidation = new RuleId(8350359768424801452L, SOURCE_NODE_REF);

    public Rule_EmailValidation() {
      super(CONCEPT, PredefinedRuleKinds.CAN_BE_CHILD, ID_EmailValidation, SOURCE_NODE_REF);
    }

    @Override
    public boolean check(@NotNull ContainmentContext context) {
      return SPropertyOperations.getString(context.getChildNode(), PROPS.email$FxHq).matches("^[A-Za-z0-9+_.-]+@(.+)$");
    }

    @Override
    public boolean appliesTo(@NotNull ContainmentContext context) {
      return true;
    }
  }

  public static final class Rule_UsernameValidation extends BaseRule<ContainmentContext> {
    private static final SNodeReference SOURCE_NODE_REF = PersistenceFacade.getInstance().createNodeReference("r:e37bf0b8-68b1-4e87-8693-247fc650f609(ECOMML.constraints)/8350359768424801467");
    public static final RuleId ID_UsernameValidation = new RuleId(8350359768424801467L, SOURCE_NODE_REF);

    public Rule_UsernameValidation() {
      super(CONCEPT, PredefinedRuleKinds.CAN_BE_CHILD, ID_UsernameValidation, SOURCE_NODE_REF);
    }

    @Override
    public boolean check(@NotNull ContainmentContext context) {
      return SPropertyOperations.getString(context.getChildNode(), PROPS.username$Fklx).matches("^[a-zA-Z0-9]([._-](?![._-])|[a-zA-Z0-9]){3,18}[a-zA-Z0-9]$");
    }

    @Override
    public boolean appliesTo(@NotNull ContainmentContext context) {
      return true;
    }
  }

  /*package*/ Administrator_ConstraintRules() {
    super(CONCEPT);
  }

  private static final class PROPS {
    /*package*/ static final SProperty email$FxHq = MetaAdapterFactory.getProperty(0xec1bc844bf74e86L, 0x9b15a8f6767d0e4eL, 0x15d9852c2ef09f42L, 0x15d9852c2ef09f83L, "email");
    /*package*/ static final SProperty username$Fklx = MetaAdapterFactory.getProperty(0xec1bc844bf74e86L, 0x9b15a8f6767d0e4eL, 0x15d9852c2ef09f42L, 0x15d9852c2ef09f74L, "username");
  }
}
