package ECOMML.constraints;

/*Generated by MPS */

import jetbrains.mps.core.aspects.feedback.api.FeedbackAspect;
import org.jetbrains.annotations.NotNull;
import java.util.stream.Stream;
import jetbrains.mps.core.aspects.feedback.api.FeedbackPerConceptDescriptor;

public final class GeneratedFeedbackAspectConstraints implements FeedbackAspect {
  @NotNull
  @Override
  public Stream<FeedbackPerConceptDescriptor> getPerConceptDescriptors() {
    return Stream.of(new Address_ConstraintsFeedback(), new Category_ConstraintsFeedback(), new Product_ConstraintsFeedback(), new ItemCart_ConstraintsFeedback(), new User_ConstraintsFeedback(), new ProductImage_ConstraintsFeedback(), new Administrator_ConstraintsFeedback());
  }
}
