package ECOMML.constraints;

/*Generated by MPS */

import jetbrains.mps.core.aspects.constraints.rules.BaseRulesConstraintsDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import java.util.List;
import jetbrains.mps.core.aspects.constraints.rules.Rule;
import java.util.Collections;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;

public final class Shipment_ConstraintRules extends BaseRulesConstraintsDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0xec1bc844bf74e86L, 0x9b15a8f6767d0e4eL, 0x4c007588fdc61c7fL, "ECOMML.structure.Shipment");


  private static final List<Rule<?>> RULES = Collections.unmodifiableList(Arrays.<Rule<?>>asList());

  @NotNull
  @Override
  public List<Rule<?>> getDeclaredRules() {
    return RULES;
  }

  /*package*/ Shipment_ConstraintRules() {
    super(CONCEPT);
  }
}
