/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.ecommerce.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class EcommerceAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("it/disim/univaq/ecommerce/xtext/parser/antlr/internal/InternalEcommerce.tokens");
	}
}
