/*
 * generated by Xtext 2.25.0
 */
package it.disim.univaq.ecommerce.xtext.parser.antlr;

import com.google.inject.Inject;
import it.disim.univaq.ecommerce.xtext.parser.antlr.internal.InternalEcommerceParser;
import it.disim.univaq.ecommerce.xtext.services.EcommerceGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class EcommerceParser extends AbstractAntlrParser {

	@Inject
	private EcommerceGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalEcommerceParser createParser(XtextTokenStream stream) {
		return new InternalEcommerceParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "EcommerceSystem";
	}

	public EcommerceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(EcommerceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
